bases:
- environments.yaml

releases:
- name: api
  chart: listshop-helm/listshop-api
  version: 1.16.0
  values:
  - "./config/api/values-{{ .Environment.Name }}.yaml"
- name: web
  chart: listshop-helm/listshop-web
  version: 2.5.4
  values:
  - "./config/web/values-{{ .Environment.Name }}.yaml"
