# Default values for listshop-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  apiUrl: https://nastyvarmits.fr/api/
  staticUrl: https://static.nastyvarmits.fr/api/
  appStoreUrl: empty
